name: task_manager
description: A task management app.
version: 1.0.0
# repository: https://github.com/leeandri/dart_cli_task_manager.git

environment:
  sdk: ^3.12.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
